export interface BrandMapping {
  brand: string;
  category: string;
}

export const CANONICAL_BRANDS: Record<string, BrandMapping> = {
  swiggy: { brand: 'SWIGGY', category: 'Food' },
  zomato: { brand: 'ZOMATO', category: 'Food' },
  uber: { brand: 'UBER', category: 'Travel' },
  ola: { brand: 'OLA', category: 'Travel' },
  rapido: { brand: 'RAPIDO', category: 'Travel' },
  amazon: { brand: 'AMAZON', category: 'Shopping' },
  flipkart: { brand: 'FLIPKART', category: 'Shopping' },
  blinkit: { brand: 'BLINKIT', category: 'Groceries' },
  zepto: { brand: 'ZEPTO', category: 'Groceries' },
  instamart: { brand: 'SWIGGY INSTAMART', category: 'Groceries' },
  myntra: { brand: 'MYNTRA', category: 'Shopping' },
  netflix: { brand: 'NETFLIX', category: 'Entertainment' },
  spotify: { brand: 'SPOTIFY', category: 'Entertainment' },
  hotstar: { brand: 'HOTSTAR', category: 'Entertainment' },
  jiomart: { brand: 'JIOMART', category: 'Groceries' },
  reliance: { brand: 'RELIANCE SMART', category: 'Groceries' },
  starbucks: { brand: 'STARBUCKS', category: 'Food' },
  mcdonald: { brand: 'MCDONALDS', category: 'Food' },
  dominos: { brand: 'DOMINOS', category: 'Food' },
  paytm: { brand: 'PAYTM', category: 'Bills' },
  airtel: { brand: 'AIRTEL', category: 'Recharge' },
  jio: { brand: 'JIO', category: 'Recharge' },
  vi: { brand: 'VODAFONE IDEA', category: 'Recharge' },
  bsnl: { brand: 'BSNL', category: 'Recharge' },
  irctc: { brand: 'IRCTC', category: 'Travel' },
  zerodha: { brand: 'ZERODHA', category: 'Investment' },
  groww: { brand: 'GROWW', category: 'Investment' },
  indmoney: { brand: 'INDMONEY', category: 'Investment' },
  angelone: { brand: 'ANGEL ONE', category: 'Investment' },
  lic: { brand: 'LIC INDIA', category: 'Bills' },
  tatapower: { brand: 'TATA POWER', category: 'Bills' },
  bescom: { brand: 'BESCOM', category: 'Bills' },
  apollo: { brand: 'APOLLO PHARMACY', category: 'Health' },
  medplus: { brand: 'MEDPLUS', category: 'Health' },
  pharmeasy: { brand: 'PHARMEASY', category: 'Health' },
  cultfit: { brand: 'CULT FIT', category: 'Health' },
  decathlon: { brand: 'DECATHLON', category: 'Shopping' },
  pvr: { brand: 'PVR CINEMAS', category: 'Entertainment' },
  inox: { brand: 'INOX LEISURE', category: 'Entertainment' },
  bookmyshow: { brand: 'BOOKMYSHOW', category: 'Entertainment' },
  hpcl: { brand: 'HP PETROL', category: 'Fuel' },
  bpcl: { brand: 'BP PETROL', category: 'Fuel' },
  iocl: { brand: 'IOC PETROL', category: 'Fuel' },
  udemy: { brand: 'UDEMY', category: 'Education' },
  coursera: { brand: 'COURSERA', category: 'Education' },
  byjus: { brand: 'BYJUS', category: 'Education' },
  hostel: { brand: 'HOSTEL', category: 'Rent' },
  stripe: { brand: 'STRIPE', category: 'Other' },
  razorpay: { brand: 'RAZORPAY', category: 'Other' },
  mpokket: { brand: 'MPOKKET', category: 'Transfer' },
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Food: ['restaurant', 'dhaba', 'cafe', 'canteen', 'food', 'bakery', 'kitchen', 'pizza', 'burger', 'sweets', 'eats', 'tea', 'chai', 'diners', 'biryani', 'delicacies'],
  Travel: ['cab', 'taxi', 'ride', 'travel', 'metro', 'railways', 'irctc', 'uber', 'ola', 'rapido', 'indigo', 'airway', 'aviation', 'hotel', 'stay', 'makemytrip', 'yatra', 'goibibo', 'bus', 'flight', 'tour'],
  Shopping: ['amazon', 'flipkart', 'myntra', 'ajio', 'shopping', 'retail', 'clothing', 'fashion', 'mall', 'mart', 'store', 'bazaar', 'electronics', 'croma', 'reliance digital', 'lifestyle', 'zara', 'h&m', 'apparel'],
  Groceries: ['grocery', 'groceries', 'kirana', 'supermarket', 'instamart', 'zepto', 'blinkit', 'jiomart', 'milk', 'dairy', 'vegetables', 'fruits', 'organic', 'mother dairy', 'superstore'],
  Bills: ['electricity', 'water', 'gas', 'power', 'board', 'limited', 'cooperative', 'insurance', 'broadband', 'telecom', 'bsnl', 'bill', 'premium', 'society', 'maintenance', 'telecommunications', 'taxes'],
  Recharge: ['recharge', 'top-up', 'prepaid', 'postpaid', 'fastag', 'dth', 'cable', 'tataplay', 'dish', 'airtel', 'jio', 'idea', 'vodafone'],
  Entertainment: ['netflix', 'spotify', 'prime video', 'hotstar', 'youtube premium', 'pvr', 'inox', 'cinema', 'movie', 'show', 'bookmyshow', 'club', 'bar', 'lounge', 'pub', 'gaming', 'steam', 'playstation', 'ticket', 'concert', 'event'],
  Health: ['pharmacy', 'chemist', 'medical', 'hospital', 'clinic', 'medplus', 'apollo', 'doctor', 'diagnostic', 'lab', 'dental', 'health', 'fitness', 'gym', 'cult.fit', 'yoga', 'therapist'],
  Fuel: ['petrol', 'diesel', 'fuel', 'cng', 'hpcl', 'bpcl', 'iocl', 'shell', 'pump', 'station', 'ev charge', 'gasoline'],
  Education: ['school', 'college', 'university', 'tuition', 'coaching', 'udemy', 'coursera', 'byjus', 'fees', 'books', 'stationery', 'academy', 'class', 'institute', 'learning'],
  Rent: ['rent', 'landlord', 'pg accommodation', 'pg stay', 'flat rent', 'monthly rent', 'deposit', 'brokerage'],
  Salary: ['salary', 'payroll', 'stipend', 'bonus', 'direct deposit', 'wages', 'compensation'],
  Investment: ['mutual fund', 'brokerage', 'zerodha', 'groww', 'indmoney', 'sip', 'fixed deposit', 'nps', 'ppf', 'shares', 'stocks', 'equity', 'gold', 'securities', 'bonds'],
  Transfer: ['transfer', 'p2p', 'payment to', 'payment from', 'sent using', 'recd:', 'received from', 'friend', 'family', 'self', 'payee', 'payer', 'gpay', 'phonepe'],
};
