import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { KeyRound, ShieldCheck, Smartphone, Lock, LogOut, FileText, ArrowRight } from 'lucide-react';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';

// --- Mock Policy Content ---
const termsContent = (
  <div className="space-y-4 text-slate-300">
    <p><strong>Last Updated: [Date]</strong></p>
    <p>Welcome to FinTrack AI. These terms and conditions outline the rules and regulations for the use of FinTrack AI's Website, located at [Website.com].</p>
    <h4 className="font-semibold text-lg text-white">1. Acceptance of Terms</h4>
    <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use FinTrack AI if you do not agree to take all of the terms and conditions stated on this page.</p>
    <h4 className="font-semibold text-lg text-white">2. License</h4>
    <p>Unless otherwise stated, FinTrack AI and/or its licensors own the intellectual property rights for all material on FinTrack AI. All intellectual property rights are reserved. You may access this from FinTrack AI for your own personal use subjected to restrictions set in these terms and conditions.</p>
    <p>You must not:</p>
    <ul className="list-disc list-inside ml-4 space-y-1">
      <li>Republish material from FinTrack AI</li>
      <li>Sell, rent or sub-license material from FinTrack AI</li>
      <li>Reproduce, duplicate or copy material from FinTrack AI</li>
      <li>Redistribute content from FinTrack AI</li>
    </ul>
    <h4 className="font-semibold text-lg text-white">3. User Data</h4>
    <p>Our Privacy Policy governs the collection, use, and disclosure of your personal data. By using our service, you agree to our Privacy Policy.</p>
    <h4 className="font-semibold text-lg text-white">4. Disclaimer</h4>
    <p>The materials on FinTrack AI's website are provided on an 'as is' basis. FinTrack AI makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
    <p>The investment suggestions provided by FinTrack AI are generated by an AI model and are for informational purposes only. They do not constitute financial advice. FinTrack AI is not a registered financial advisor. All investments carry risk, and you should consult with a qualified professional before making any financial decisions.</p>
    {/* Add more placeholder text as needed */}
  </div>
);

const privacyContent = (
  <div className="space-y-4 text-slate-300">
    <p><strong>Last Updated: [Date]</strong></p>
    <p>FinTrack AI ("us", "we", or "our") operates the [Website.com] website (the "Service").</p>
    <h4 className="font-semibold text-lg text-white">1. Information Collection and Use</h4>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <ul className="list-disc list-inside ml-4 space-y-1">
      <li><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data").</li>
      <li><strong>Transaction Data:</strong> To provide automated tracking, our companion mobile application requests permission to read SMS messages. We only parse messages identified as financial transactions. This data is encrypted, stored securely, and is never shared with third parties without your explicit consent.</li>
      <li><strong>Usage Data:</strong> We may also collect information how the Service is accessed and used ("Usage Data").</li>
    </ul>
    <h4 className="font-semibold text-lg text-white">2. Data Security</h4>
    <p>The security of your data is important to us. We use strong encryption (both in transit and at rest) and industry-standard security practices to protect your information. However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>
    <h4 className="font-semibold text-lg text-white">3. Service Providers</h4>
    <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. This includes the use of Generative AI models to provide financial suggestions. Your anonymized data may be used to improve these models, but will never be linked back to you personally.</p>
    <h4 className="font-semibold text-lg text-white">4. Changes to This Privacy Policy</h4>
    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    {/* Add more placeholder text as needed */}
  </div>
);

// --- Component ---

// Mock data for active sessions
const initialSessions = [
  { id: '1', browser: 'Chrome on Windows', location: 'Ghaziabad, IN (Current)', isCurrent: true },
  { id: '2', browser: 'Safari on iPhone 15', location: 'Mumbai, IN', isCurrent: false },
  { id: '3', browser: 'Firefox on MacOS', location: 'Unknown Location', isCurrent: false },
];

const SecurityPage = () => {
  const [is2FAEnabled, setIs2FAEnabled] = useState(true);
  const [isAppLockEnabled, setIsAppLockEnabled] = useState(false);
  const [activeSessions, setActiveSessions] = useState(initialSessions);
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');

  const [isPolicyOpen, setIsPolicyOpen] = useState(false);
  const [panelTitle, setPanelTitle] = useState("");
  const [panelContent, setPanelContent] = useState<React.ReactNode>(null);

  const handlePasswordChange = () => {
    if (currentPassword === '' || newPassword === '') {
      toast.error("Please fill in both password fields.");
      return;
    }
    // In a real app, you'd send this to your backend
    toast.success("Password updated successfully!");
    setCurrentPassword('');
    setNewPassword('');
  };

  const handleToggle2FA = (enabled: boolean) => {
    setIs2FAEnabled(enabled);
    toast.success(`Two-Factor Authentication ${enabled ? 'Enabled' : 'Disabled'}`);
  };

  const handleToggleAppLock = (enabled: boolean) => {
    setIsAppLockEnabled(enabled);
    toast.success(`App Lock ${enabled ? 'Enabled' : 'Disabled'}`);
  };

  const handleLogoutSession = (sessionId: string) => {
    setActiveSessions(prev => prev.filter(session => session.id !== sessionId));
    toast.info("Session logged out.");
  };

  const openPolicyPanel = (type: 'terms' | 'privacy') => {
    if (type === 'terms') {
      setPanelTitle("Terms of Service");
      setPanelContent(termsContent);
    } else {
      setPanelTitle("Privacy Policy");
      setPanelContent(privacyContent);
    }
    setIsPolicyOpen(true);
  };

  return (
    <div className="p-4 sm:p-8 rounded-lg min-h-screen text-white overflow-hidden relative">
      {/* Animated background blobs */}
      <div className="absolute top-0 left-0 w-72 h-72 bg-blue-500/30 rounded-full filter blur-3xl opacity-50 animate-blob"></div>
      <div className="absolute top-1/2 left-1/3 w-72 h-72 bg-purple-500/30 rounded-full filter blur-3xl opacity-50 animate-blob animation-delay-2000"></div>
      <div className="absolute bottom-0 right-0 w-72 h-72 bg-green-500/30 rounded-full filter blur-3xl opacity-50 animate-blob animation-delay-4000"></div>

      <div className="relative z-10 space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-white">Security & Privacy</h1>
          <p className="text-slate-400">Manage your password, authentication, and active sessions.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* Column 1: Password & 2FA */}
          <div className="space-y-8">
            {/* Change Password Card */}
            <Card className="bg-slate-800/40 backdrop-blur-2xl border-white/10 shadow-lg neon-glow-hover">
              <CardHeader className="flex flex-row items-center gap-4">
                <KeyRound className="w-8 h-8 text-primary" />
                <div>
                  <CardTitle className="text-white">Change Password</CardTitle>
                  <CardDescription className="text-slate-400">Update your password regularly to keep your account secure.</CardDescription>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="current-password" className="text-slate-300">Current Password</Label>
                  <Input 
                    id="current-password" 
                    type="password" 
                    value={currentPassword}
                    onChange={(e) => setCurrentPassword(e.target.value)}
                    className="bg-slate-700/50 border-slate-600 text-white focus:ring-primary/50 focus:border-primary/50" 
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="new-password" className="text-slate-300">New Password</Label>
                  <Input 
                    id="new-password" 
                    type="password" 
                    value={newPassword}
                    onChange={(e) => setNewPassword(e.target.value)}
                    className="bg-slate-700/50 border-slate-600 text-white focus:ring-primary/50 focus:border-primary/50" 
                  />
                </div>
                <Button 
                  onClick={handlePasswordChange}
                  className="w-full bg-primary/80 text-white backdrop-blur-md border border-primary/50 shadow-lg shadow-primary/30 hover:bg-primary"
                >
                  Update Password
                </Button>
              </CardContent>
            </Card>

            {/* 2FA and App Lock Card */}
            <Card className="bg-slate-800/40 backdrop-blur-2xl border-white/10 shadow-lg neon-glow-hover">
              <CardHeader>
                <CardTitle className="text-white">Authentication Settings</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex items-center justify-between p-4 bg-slate-900/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <ShieldCheck className="w-6 h-6 text-green-400" />
                    <div>
                      <h4 className="font-semibold text-white">Two-Factor Authentication</h4>
                      <p className="text-sm text-slate-400">Add an extra layer of security to your account.</p>
                    </div>
                  </div>
                  <Switch
                    checked={is2FAEnabled}
                    onCheckedChange={handleToggle2FA}
                  />
                </div>
                <div className="flex items-center justify-between p-4 bg-slate-900/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <Lock className="w-6 h-6 text-blue-400" />
                    <div>
                      <h4 className="font-semibold text-white">App Lock</h4>
                      <p className="text-sm text-slate-400">Require PIN or Biometrics to open the app.</p>
                    </div>
                  </div>
                  <Switch
                    checked={isAppLockEnabled}
                    onCheckedChange={handleToggleAppLock}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Terms and Conditions Card */}
            <Dialog open={isPolicyOpen} onOpenChange={setIsPolicyOpen}>
              <Card className="bg-slate-800/40 backdrop-blur-2xl border-white/10 shadow-lg neon-glow-hover">
                <CardHeader className="flex flex-row items-center gap-4">
                  <FileText className="w-8 h-8 text-primary" />
                  <div>
                    <CardTitle className="text-white">Terms & Privacy</CardTitle>
                    <CardDescription className="text-slate-400">Review our policies to understand your rights.</CardDescription>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <DialogTrigger asChild>
                    <Button 
                      variant="outline" 
                      className="w-full justify-between group bg-slate-700/50 border-slate-600 text-white hover:bg-slate-700 hover:text-white"
                      onClick={() => openPolicyPanel('terms')}
                    >
                      View Terms of Service
                      <ArrowRight className="w-4 h-4 text-slate-400 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </DialogTrigger>
                  <DialogTrigger asChild>
                    <Button 
                      variant="outline" 
                      className="w-full justify-between group bg-slate-700/50 border-slate-600 text-white hover:bg-slate-700 hover:text-white"
                      onClick={() => openPolicyPanel('privacy')}
                    >
                      View Privacy Policy
                      <ArrowRight className="w-4 h-4 text-slate-400 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </DialogTrigger>
                </CardContent>
              </Card>

              <DialogContent className="sm:max-w-3xl h-[80vh] bg-slate-800/80 backdrop-blur-lg border-white/10 text-white flex flex-col">
                <DialogHeader>
                  <DialogTitle className="text-white text-2xl">{panelTitle}</DialogTitle>
                </DialogHeader>
                <ScrollArea className="flex-1 pr-6">
                  {panelContent}
                </ScrollArea>
              </DialogContent>
            </Dialog>
          </div>

          {/* Column 2: Active Sessions */}
          <Card className="bg-slate-800/40 backdrop-blur-2xl border-white/10 shadow-lg neon-glow-hover">
            <CardHeader className="flex flex-row items-center gap-4">
              <Smartphone className="w-8 h-8 text-primary" />
              <div>
                <CardTitle className="text-white">Active Sessions</CardTitle>
                <CardDescription className="text-slate-400">This is a list of devices that have logged into your account.</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {activeSessions.map((session) => (
                <div key={session.id} className="flex items-center justify-between p-4 bg-slate-900/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <Smartphone className="w-6 h-6 text-slate-400" />
                    <div>
                      <h4 className="font-semibold text-white">{session.browser}</h4>
                      <p className="text-sm text-slate-400">{session.location}</p>
                    </div>
                  </div>
                  {session.isCurrent ? (
                    <span className="text-sm font-medium text-green-400">Active Now</span>
                  ) : (
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => handleLogoutSession(session.id)}
                      className="text-red-400 border-red-400/50 hover:bg-red-900/50 hover:text-red-300"
                    >
                      <LogOut className="mr-2 h-4 w-4" />
                      Log out
                    </Button>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default SecurityPage;